services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    stdin_open: true